<?php

namespace Database\Seeders;

use App\Models\Hymn;
use Illuminate\Database\Seeder;

class HymnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hymns = [
            ['number' => 1, 'title' => 'Blest and Happy Is the Man', 'duration' => '1:51', 'time_signature' => '4/4'],
            ['number' => 2, 'title' => 'Psalm 1', 'duration' => '1:49', 'time_signature' => '4/4'],
            ['number' => 3, 'title' => 'Trust in God and Stand in Awe', 'duration' => '1:52', 'time_signature' => '4/4'],
            ['number' => 4, 'title' => 'Give Ear Unto My Words, O Lord', 'duration' => '2:35', 'time_signature' => '4/4'],
            ['number' => 5, 'title' => 'Turn O God and Save Me', 'duration' => '1:59', 'time_signature' => '4/4'],
            ['number' => 6, 'title' => 'How Excellent is Thy Name', 'duration' => '1:53', 'time_signature' => '4/4'],
            ['number' => 7, 'title' => 'How Excellent In All The Earth', 'duration' => '1:47', 'time_signature' => '4/4'],
            ['number' => 8, 'title' => 'I Will Praise Thee O Eternal', 'duration' => '1:49', 'time_signature' => '4/4'],
            ['number' => 9, 'title' => 'Declare His Works to All Nations!', 'duration' => '2:00', 'time_signature' => '4/4'],
            ['number' => 10, 'title' => 'Who Shall Dwell on Thy Holy Hill', 'duration' => '1:31', 'time_signature' => '4/4'],
            ['number' => 11, 'title' => 'The Heavens God\'s Glory Do Declare', 'duration' => '2:43', 'time_signature' => '3/4'],
            ['number' => 12, 'title' => 'Most Perfect is the Law of God', 'duration' => '1:35', 'time_signature' => '4/4'],
            ['number' => 13, 'title' => 'The Lord\'s My Shepherd (Crimond)', 'duration' => '2:30', 'time_signature' => '3/4'],
            ['number' => 14, 'title' => 'The Lord is My Shepherd (Montgomery)', 'duration' => '2:50', 'time_signature' => '3/4'],
            ['number' => 15, 'title' => 'The Lord\'s My Shepherd (Havergal)', 'duration' => '1:46', 'time_signature' => '3/2'],
            ['number' => 16, 'title' => 'My Shepherd Will Supply My Need', 'duration' => '3:14', 'time_signature' => '3/4'],
            ['number' => 17, 'title' => 'To Thee I Lift My Soul', 'duration' => '2:06', 'time_signature' => '4/4'],
            ['number' => 18, 'title' => 'Our God Is Good And Upright', 'duration' => '2:05', 'time_signature' => '4/4'],
            ['number' => 19, 'title' => 'Mine Eyes Upon the Lord', 'duration' => '1:52', 'time_signature' => '4/4'],
            ['number' => 20, 'title' => 'They Are Blest Who Are Forgiven', 'duration' => '1:50', 'time_signature' => '3/4'],
            ['number' => 21, 'title' => 'Blessed is the Nation God is For', 'duration' => '2:21', 'time_signature' => '4/4'],
            ['number' => 22, 'title' => 'I Will Bless the Lord At All Times', 'duration' => '1:21', 'time_signature' => '4/4'],
            ['number' => 23, 'title' => 'Turn Thou From Evil', 'duration' => '1:52', 'time_signature' => '4/4'],
            ['number' => 24, 'title' => 'Wait and Hope and Look for God', 'duration' => '2:04', 'time_signature' => '4/4'],
            ['number' => 25, 'title' => 'Righteous Judge', 'duration' => '1:21', 'time_signature' => '4/4'],
            ['number' => 26, 'title' => 'O God We Have Heard', 'duration' => '1:37', 'time_signature' => '3/4'],
            ['number' => 27, 'title' => 'God Is Our Refuge', 'duration' => '1:45', 'time_signature' => '4/4'],
            ['number' => 28, 'title' => 'Come See the Works of God', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 29, 'title' => 'Mount Zion Stands Most Beautiful', 'duration' => '1:56', 'time_signature' => '4/4'],
            ['number' => 30, 'title' => 'Give Thanks and Offer Praise', 'duration' => '1:47', 'time_signature' => '4/4'],
            ['number' => 31, 'title' => 'In Thy Lovingkindness Lord', 'duration' => '2:50', 'time_signature' => '4/4'],
            ['number' => 32, 'title' => 'Save Me O God By Thy Great Name', 'duration' => '1:54', 'time_signature' => '4/4'],
            ['number' => 33, 'title' => 'But As For Me I\'ll Call On God', 'duration' => '1:58', 'time_signature' => '3/4'],
            ['number' => 34, 'title' => 'Give Ear Unto My Prayer O God', 'duration' => '1:59', 'time_signature' => '4/4'],
            ['number' => 35, 'title' => 'God is My Rock My Salvation', 'duration' => '2:13', 'time_signature' => '3/4'],
            ['number' => 36, 'title' => 'Joyfully Sing and Praise God!', 'duration' => '2:53', 'time_signature' => '4/4'],
            ['number' => 37, 'title' => 'O God Forsake Me Not', 'duration' => '2:03', 'time_signature' => '3/4'],
            ['number' => 38, 'title' => 'For Even From My Youth O God', 'duration' => '1:52', 'time_signature' => '4/4'],
            ['number' => 39, 'title' => 'His Name Is Great!', 'duration' => '2:27', 'time_signature' => '6/8'],
            ['number' => 40, 'title' => 'O Thou the Shepherd of Israel Art', 'duration' => '2:12', 'time_signature' => '3/4'],
            ['number' => 41, 'title' => 'Thou Shepherd That Dost Israel Keep', 'duration' => '2:03', 'time_signature' => '4/4'],
            ['number' => 42, 'title' => 'Praise the Eternal With a Psalm', 'duration' => '2:29', 'time_signature' => '4/4'],
            ['number' => 43, 'title' => 'Sing Songs of Praise to Him', 'duration' => '1:55', 'time_signature' => '4/4'],
            ['number' => 44, 'title' => 'O Lord of Hosts, My King My God', 'duration' => '2:08', 'time_signature' => '4/4'],
            ['number' => 45, 'title' => 'How Lovely Are Thy Dwellings', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 46, 'title' => 'How Long Eternal Hide Thou Away', 'duration' => '1:25', 'time_signature' => '4/4'],
            ['number' => 47, 'title' => 'Zion Founded On The Mountains', 'duration' => '1:48', 'time_signature' => '3/4'],
            ['number' => 48, 'title' => 'O God Our Help in Ages Past', 'duration' => '1:27', 'time_signature' => '4/4'],
            ['number' => 49, 'title' => 'How Good It Is to Thank the Lord', 'duration' => '2:00', 'time_signature' => '4/4'],
            ['number' => 50, 'title' => 'Sabbath Song', 'duration' => '2:22', 'time_signature' => '4/4'],
            ['number' => 51, 'title' => 'It Is Good To Sing Thy Praises', 'duration' => '2:07', 'time_signature' => '4/4'],
            ['number' => 52, 'title' => 'O Come and Let Us Worship Him', 'duration' => '1:53', 'time_signature' => '4/4'],
            ['number' => 53, 'title' => 'O Come Let Us Sing to the Lord', 'duration' => '2:04', 'time_signature' => '4/4'],
            ['number' => 54, 'title' => 'The Lord Eternal Reigneth', 'duration' => '1:32', 'time_signature' => '3/4'],
            ['number' => 55, 'title' => 'O Sing a New Song to the Lord', 'duration' => '2:31', 'time_signature' => '4/4'],
            ['number' => 56, 'title' => 'Sing Praises and Rejoice', 'duration' => '2:34', 'time_signature' => '4/4'],
            ['number' => 57, 'title' => 'Holy Mighty Majesty', 'duration' => '1:53', 'time_signature' => '4/4'],
            ['number' => 58, 'title' => 'Sing to the Lord With Cheerful Voice', 'duration' => '1:28', 'time_signature' => '4/4'],
            ['number' => 59, 'title' => 'Come Before His Presence With Singing', 'duration' => '2:01', 'time_signature' => '4/4'],
            ['number' => 60, 'title' => 'He Shall Reign Forevermore!', 'duration' => '2:31', 'time_signature' => '3/4'],
            ['number' => 61, 'title' => 'O My Soul Bless God the Father', 'duration' => '2:08', 'time_signature' => '4/4'],
            ['number' => 62, 'title' => 'We Give Thanks to Our Redeemer', 'duration' => '1:30', 'time_signature' => '4/4'],
            ['number' => 63, 'title' => 'Bless the Lord Eternal O My Soul', 'duration' => '2:33', 'time_signature' => '4/4'],
            ['number' => 64, 'title' => 'O Give Thanks and Praise the Eternal', 'duration' => '2:13', 'time_signature' => '3/4'],
            ['number' => 65, 'title' => 'O Praise the Lord For He is Good', 'duration' => '2:10', 'time_signature' => '4/4'],
            ['number' => 66, 'title' => 'O That Men Would Praise Their God', 'duration' => '2:05', 'time_signature' => '3/4'],
            ['number' => 67, 'title' => 'When Israel Out of Egypt Went', 'duration' => '2:29', 'time_signature' => '3/4'],
            ['number' => 68, 'title' => 'Praise Belongs to God', 'duration' => '1:52', 'time_signature' => '4/4'],
            ['number' => 69, 'title' => 'Praise the Lord on High', 'duration' => '1:54', 'time_signature' => '4/4'],
            ['number' => 70, 'title' => 'O Give Thanks Unto Our God', 'duration' => '2:23', 'time_signature' => '4/4'],
            ['number' => 71, 'title' => 'How Shall the Young Direct Their Way', 'duration' => '1:57', 'time_signature' => '3/4'],
            ['number' => 72, 'title' => 'O How Love I Thy Law', 'duration' => '1:30', 'time_signature' => '3/4'],
            ['number' => 73, 'title' => 'How I Love Thy Law O Lord', 'duration' => '2:34', 'time_signature' => '4/4'],
            ['number' => 74, 'title' => 'I Hate the Thoughts of Vanity', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 75, 'title' => 'Unto the Hills I Lift My Eyes', 'duration' => '1:23', 'time_signature' => '3/4'],
            ['number' => 76, 'title' => 'Unless the Lord Shall Build the House', 'duration' => '2:04', 'time_signature' => '4/4'],
            ['number' => 77, 'title' => 'Blest and Happy Is He', 'duration' => '1:06', 'time_signature' => '3/4'],
            ['number' => 78, 'title' => 'Praise God\'s Name', 'duration' => '2:02', 'time_signature' => '4/4'],
            ['number' => 79, 'title' => 'His Mercy Never Fails', 'duration' => '2:28', 'time_signature' => '4/4'],
            ['number' => 80, 'title' => 'By the Waters of Babylon', 'duration' => '2:12', 'time_signature' => '4/4'],
            ['number' => 81, 'title' => 'Lord I Will Praise Thee!', 'duration' => '2:40', 'time_signature' => '4/4'],
            ['number' => 82, 'title' => 'The Servant\'s Prayer', 'duration' => '1:23', 'time_signature' => '3/4'],
            ['number' => 83, 'title' => 'O Lord Thou Art My God and King!', 'duration' => '1:23', 'time_signature' => '4/4'],
            ['number' => 84, 'title' => 'Hallelujah! Praise God!', 'duration' => '1:29', 'time_signature' => '3/4'],
            ['number' => 85, 'title' => 'O Sing Ye Hallelujah!', 'duration' => '2:36', 'time_signature' => '4/4'],
            ['number' => 86, 'title' => 'Praise the Lord Sing Praise', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 87, 'title' => 'Praise Ye the Lord!', 'duration' => '2:12', 'time_signature' => '4/4'],
            ['number' => 88, 'title' => 'I Will Sing Unto the Eternal', 'duration' => '2:04', 'time_signature' => '4/4'],
            ['number' => 89, 'title' => 'Love the Lord Your God', 'duration' => '2:03', 'time_signature' => null],
            ['number' => 90, 'title' => 'Thee Will I Love O Lord', 'duration' => '2:34', 'time_signature' => '4/4'],
            ['number' => 91, 'title' => 'Stand Up and Bless the Lord', 'duration' => '1:18', 'time_signature' => '4/4'],
            ['number' => 92, 'title' => 'Christ Shall Have Dominion', 'duration' => '3:36', 'time_signature' => '4/4'],
            ['number' => 93, 'title' => 'Arise and Sing His Praise', 'duration' => '2:36', 'time_signature' => '3/4'],
            ['number' => 94, 'title' => 'From All Who Dwell Below the Skies', 'duration' => '2:26', 'time_signature' => '4/4'],
            ['number' => 95, 'title' => 'The Lord God Reigns', 'duration' => '2:03', 'time_signature' => '3/2'],
            ['number' => 96, 'title' => 'The Mountain of the Lord', 'duration' => '2:39', 'time_signature' => '4/4'],
            ['number' => 97, 'title' => 'Behold, the Day Will Come', 'duration' => '2:34', 'time_signature' => '4/4'],
            ['number' => 98, 'title' => 'Hearts of the Fathers', 'duration' => '2:20', 'time_signature' => '4/4'],
            ['number' => 99, 'title' => 'Consider the Lillies', 'duration' => '1:52', 'time_signature' => '6/8'],
            ['number' => 100, 'title' => 'Seek Ye First', 'duration' => '1:28', 'time_signature' => '4/4'],
            ['number' => 101, 'title' => 'Go Ye Therefore Into All the World', 'duration' => '2:16', 'time_signature' => '4/4'],
            ['number' => 102, 'title' => 'God Speaks To Us', 'duration' => '2:14', 'time_signature' => '4/4'],
            ['number' => 103, 'title' => 'Not Many Wise Men Now Are Called', 'duration' => '2:01', 'time_signature' => '4/4'],
            ['number' => 104, 'title' => 'The Trumpet Shall Sound', 'duration' => '3:00', 'time_signature' => '4/4'],
            ['number' => 105, 'title' => 'Ambassadors for Christ', 'duration' => '3:53', 'time_signature' => '4/4'],
            ['number' => 106, 'title' => 'If I Have Not Charity', 'duration' => '2:37', 'time_signature' => '4/4'],
            ['number' => 107, 'title' => 'Think On These Things', 'duration' => '1:21', 'time_signature' => '4/4'],
            ['number' => 108, 'title' => 'A Chosen Generation', 'duration' => '1:56', 'time_signature' => '4/4'],
            ['number' => 109, 'title' => 'The New Jerusalem', 'duration' => '2:31', 'time_signature' => '4/4'],
            ['number' => 110, 'title' => 'All Things Bright and Beautiful', 'duration' => '2:54', 'time_signature' => '4/4'],
            ['number' => 111, 'title' => 'Keep God\'s Sabbath Holy', 'duration' => '2:41', 'time_signature' => '4/4'],
            ['number' => 112, 'title' => 'On the Sabbath Day', 'duration' => '2:14', 'time_signature' => '3/4'],
            ['number' => 113, 'title' => 'Come Ye Thankful People Come', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 114, 'title' => 'May Your Blessing Be Upon Us', 'duration' => '1:47', 'time_signature' => '3/4'],
            ['number' => 115, 'title' => 'Everybody Worship', 'duration' => '2:43', 'time_signature' => '2/2'],
            ['number' => 116, 'title' => 'As For Me and My House', 'duration' => '2:50', 'time_signature' => '4/4'],
            ['number' => 117, 'title' => 'Now Thank We All Our God', 'duration' => '2:25', 'time_signature' => '4/4'],
            ['number' => 118, 'title' => 'Search Me O God', 'duration' => '2:30', 'time_signature' => '3/4'],
            ['number' => 119, 'title' => 'Teach Me Thy Way', 'duration' => '2:30', 'time_signature' => '3/4'],
            ['number' => 120, 'title' => 'We Hope in Your Mercy', 'duration' => '1:36', 'time_signature' => '3/4'],
            ['number' => 121, 'title' => 'As the Deer', 'duration' => '2:27', 'time_signature' => '4/4'],
            ['number' => 122, 'title' => 'Great is the Lord', 'duration' => '1:59', 'time_signature' => '4/4'],
            ['number' => 123, 'title' => 'Wake My Heart', 'duration' => '2:50', 'time_signature' => '4/4'],
            ['number' => 124, 'title' => 'Our Thanks O God For Parents', 'duration' => '1:34', 'time_signature' => '4/4'],
            ['number' => 125, 'title' => 'God of Grace and God of Glory', 'duration' => '2:02', 'time_signature' => '4/4'],
            ['number' => 126, 'title' => 'Men and Children Everywhere', 'duration' => '2:11', 'time_signature' => '4/4'],
            ['number' => 127, 'title' => 'We Will Glorify', 'duration' => '1:26', 'time_signature' => '3/4'],
            ['number' => 128, 'title' => 'Glorious Things of Thee Are Spoken', 'duration' => '2:20', 'time_signature' => '4/4'],
            ['number' => 129, 'title' => 'How Great Thou Art', 'duration' => '4:14', 'time_signature' => '4/4'],
            ['number' => 130, 'title' => 'To God Be the Glory', 'duration' => '2:56', 'time_signature' => '3/4'],
            ['number' => 131, 'title' => 'O Worship The King', 'duration' => '1:59', 'time_signature' => '3/4'],
            ['number' => 132, 'title' => 'How Good and How Pleasant', 'duration' => '3:00', 'time_signature' => '3/4'],
            ['number' => 133, 'title' => 'We Are God\'s People', 'duration' => '3:03', 'time_signature' => '4/4'],
            ['number' => 134, 'title' => 'Glory to Thy Name', 'duration' => '2:35', 'time_signature' => '4/4'],
            ['number' => 135, 'title' => 'Great God Who Made the Universe', 'duration' => '3:07', 'time_signature' => '3/4'],
            ['number' => 136, 'title' => 'Let All Things Now Living', 'duration' => '2:08', 'time_signature' => '3/4'],
            ['number' => 137, 'title' => 'Praise My Soul the King of Heaven', 'duration' => '2:28', 'time_signature' => '4/4'],
            ['number' => 138, 'title' => 'Praise Ye the Lord the Almighty', 'duration' => '2:31', 'time_signature' => '3/4'],
            ['number' => 139, 'title' => 'Be Now My Vision', 'duration' => '2:01', 'time_signature' => '3/4'],
            ['number' => 140, 'title' => 'All Hail the Power', 'duration' => '2:25', 'time_signature' => '4/4'],
            ['number' => 141, 'title' => 'The Prophet Has Written', 'duration' => '1:49', 'time_signature' => '3/4'],
            ['number' => 142, 'title' => 'Be At Rest Child of God', 'duration' => '2:50', 'time_signature' => '4/4'],
            ['number' => 143, 'title' => 'Be Not Afraid My People', 'duration' => '2:03', 'time_signature' => '4/4'],
            ['number' => 144, 'title' => 'All Must Be Well', 'duration' => '2:37', 'time_signature' => '4/4'],
            ['number' => 145, 'title' => 'I Sing the Mighty Power of God', 'duration' => '1:57', 'time_signature' => '4/4'],
            ['number' => 146, 'title' => 'In Days of Old', 'duration' => '2:59', 'time_signature' => '4/4'],
            ['number' => 147, 'title' => 'Great is Thy Faithfulness', 'duration' => '3:14', 'time_signature' => '3/4'],
            ['number' => 148, 'title' => 'God is Calling Children', 'duration' => '1:33', 'time_signature' => '4/4'],
            ['number' => 149, 'title' => 'God Our Father Christ Our Brother', 'duration' => '2:34', 'time_signature' => '4/4'],
            ['number' => 150, 'title' => 'Seek You First the Kingdom of God', 'duration' => '3:25', 'time_signature' => '4/4'],
            ['number' => 151, 'title' => 'All Glory Laud and Honor', 'duration' => '1:58', 'time_signature' => '4/4'],
            ['number' => 152, 'title' => 'Go Into the World', 'duration' => '1:59', 'time_signature' => '4/4'],
            ['number' => 153, 'title' => 'Suffer the Children', 'duration' => '3:23', 'time_signature' => '3/4'],
            ['number' => 154, 'title' => 'Creator God the Mighty One', 'duration' => '1:54', 'time_signature' => '3/4'],
            ['number' => 155, 'title' => 'God So Loved the World', 'duration' => '1:52', 'time_signature' => '3/4'],
            ['number' => 156, 'title' => 'The One Whom the Father Sends', 'duration' => '3:38', 'time_signature' => '4/4'],
            ['number' => 157, 'title' => 'By This Shall All Men Know', 'duration' => '3:15', 'time_signature' => '4/4'],
            ['number' => 158, 'title' => 'The God of Abraham', 'duration' => '2:09', 'time_signature' => '4/4'],
            ['number' => 159, 'title' => 'Praise the Lord', 'duration' => '2:11', 'time_signature' => '4/4'],
            ['number' => 160, 'title' => 'There is Joy in My Heart', 'duration' => '2:43', 'time_signature' => '2/2'],
            ['number' => 161, 'title' => 'From the Realms of Unseen Glor', 'duration' => '1:50', 'time_signature' => '4/4'],
            ['number' => 162, 'title' => 'We Praise Thee O God Our Redeemer', 'duration' => '1:39', 'time_signature' => '3/4'],
            ['number' => 163, 'title' => 'At One With God', 'duration' => '2:49', 'time_signature' => '3/4'],
            ['number' => 164, 'title' => 'For I Am Called By Your Name', 'duration' => '1:54', 'time_signature' => '6/8'],
            ['number' => 165, 'title' => 'All Things Work Together', 'duration' => '3:37', 'time_signature' => '4/4'],
            ['number' => 166, 'title' => 'Rejoice Be At One', 'duration' => '2:00', 'time_signature' => '3/4'],
            ['number' => 167, 'title' => 'God Will See Us Through', 'duration' => '2:02', 'time_signature' => '4/4'],
            ['number' => 168, 'title' => 'Thank You Lord', 'duration' => '2:37', 'time_signature' => '4/4'],
            ['number' => 169, 'title' => 'The Church\'s One Foundation', 'duration' => '2:11', 'time_signature' => '4/4'],
            ['number' => 170, 'title' => 'Fight the Good Fight', 'duration' => '2:32', 'time_signature' => '4/4'],
            ['number' => 171, 'title' => 'One Faith One Love', 'duration' => '2:58', 'time_signature' => '4/4'],
            ['number' => 172, 'title' => 'Have One Mind', 'duration' => '2:23', 'time_signature' => '4/4'],
            ['number' => 173, 'title' => 'Rejoice the Lord the King', 'duration' => '1:33', 'time_signature' => '4/4'],
            ['number' => 174, 'title' => 'Moses\' New Song', 'duration' => '2:36', 'time_signature' => '4/4'],
            ['number' => 175, 'title' => 'Onward Christian Soldiers', 'duration' => '3:33', 'time_signature' => '4/4'],
            ['number' => 176, 'title' => 'Forgive and You Shall Be Forgiven', 'duration' => '3:35', 'time_signature' => '4/4'],
            ['number' => 177, 'title' => 'Covenant People', 'duration' => '2:23', 'time_signature' => '4/4'],
            ['number' => 178, 'title' => 'For the Beauty of the Earth', 'duration' => '2:21', 'time_signature' => '4/4'],
            ['number' => 179, 'title' => 'Be You Holy', 'duration' => '1:27', 'time_signature' => '3/4'],
            ['number' => 180, 'title' => 'God Be With You', 'duration' => '1:59', 'time_signature' => '4/4'],
            ['number' => 181, 'title' => 'United We Stand', 'duration' => '3:21', 'time_signature' => '4/4'],
            ['number' => 182, 'title' => 'God\'s Message', 'duration' => '1:53', 'time_signature' => '4/4'],
            ['number' => 183, 'title' => 'O God Of Every Nation', 'duration' => '2:29', 'time_signature' => '4/4'],
            ['number' => 184, 'title' => 'Lamb of God', 'duration' => '2:38', 'time_signature' => '4/4'],
            ['number' => 185, 'title' => 'Mine Eyes Have Seen the Glory', 'duration' => '2:19', 'time_signature' => '4/4'],
            ['number' => 186, 'title' => 'Worthy of Worship', 'duration' => '2:39', 'time_signature' => '3/4'],
            ['number' => 187, 'title' => 'Hymn of Unity', 'duration' => '2:27', 'time_signature' => '4/4'],
            ['number' => 188, 'title' => 'Crown Him With Many Crowns', 'duration' => '2:05', 'time_signature' => '4/4'],
            ['number' => 189, 'title' => 'City of God', 'duration' => '3:00', 'time_signature' => '3/4'],
            ['number' => 190, 'title' => 'It Won\'t Be Long Now', 'duration' => '2:09', 'time_signature' => '3/4'],
            ['number' => 191, 'title' => 'When Christ Shall Come', 'duration' => '2:39', 'time_signature' => '4/4'],
        ];

        Hymn::query()->upsert($hymns, uniqueBy: ['number']);
    }
}
