<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sermonTags = [
            'Adoption',
            'Adultery',
            'Anxiety',
            'Armageddon',
            'Atonement',
            'Beast',
            'Birthright Promises',
            'Born Again',
            'Calendar',
            'Childrearing',
            'Children',
            'Children Of God',
            'Church',
            'Commandments',
            'Commitment',
            'Community',
            'Compassion',
            'Correction',
            'Covet',
            'Cross',
            'Day Of The Lord',
            'Deacons',
            'Death',
            'Deliverance',
            'Discipleship',
            'Eighth Day',
            'Elders',
            'Evangelism',
            'Faith',
            'False Prophet',
            'Family',
            'Famine',
            'Fasting',
            'Fear',
            'Feast',
            'Firstfruits',
            'Following God',
            'Foreknew',
            'Forever',
            'Forgiveness',
            'Generosity',
            'God\'s Faithfulness',
            'God\'s Love',
            'God\'s Plan',
            'God\'s Power',
            'God\'s Presence',
            'Gossip',
            'Grace',
            'Gratitude',
            'Harvest',
            'Healing',
            'Health',
            'Heaven',
            'Heavenly Signs',
            'Heirs',
            'Holiness',
            'Holy Spirit',
            'Homosexuality',
            'Hope',
            'Identity in Christ',
            'Integrity',
            'Israel',
            'Jesus Christ',
            'Joy',
            'Judah',
            'Kingdom of God',
            'Labor',
            'Law',
            'Laying On Of Hands',
            'Leadership',
            'Levi',
            'Longsuffering',
            'Love',
            'Man',
            'Marriage',
            'Medicine',
            'Mercy',
            'Ministry',
            'Missions',
            'Oaths',
            'Obedience',
            'Overcoming',
            'Parenting',
            'Passover',
            'Patience',
            'Peace',
            'Pentecost',
            'Persecution',
            'Prayer',
            'Priest',
            'Purpose',
            'Repentance',
            'Resurrection',
            'Revival',
            'Reward',
            'Righteousness',
            'Sabbath',
            'Salvation',
            'Scepter Promises',
            'Second Death',
            'Service',
            'Sickness',
            'Signs And Wonders',
            'Sin',
            'Slave',
            'Spiritual Growth',
            'Statutes And Judgments',
            'Stewardship',
            'Suffering',
            'Tabernacles',
            'Taxes',
            'Temple',
            'Temptation',
            'Thanks',
            'Throne',
            'Time',
            'Trials',
            'Tribulation',
            'Trumpets',
            'Trust',
            'Unity',
            'Unleavened Bread',
            'White Throne Judgment',
            'Work and Faith',
            'Works',
            'Worship',
            'Youth',
        ];

        $hymnTags = [
            'Christian Living',
            'Church Of God, Church Commission, God\'s People',
            'Comfort, Encouragement',
            'Commitment',
            'Confidence, Courage',
            'Creator, Creation',
            'Family',
            'Fellowship',
            'God The Father',
            'God\'s Blessings',
            'God\'s Faithfulness',
            'God\'s Greatness And Power',
            'God\'s Guidance And Care',
            'God\'s Plan',
            'Heritage',
            'Holy Days, Sabbath',
            'Hope',
            'Jesus Christ - Lamb Of God',
            'Jesus Christ - Lord, Savior And King',
            'Jesus Christ - Second Coming',
            'Kingdom Of God',
            'Law Of God',
            'Love',
            'Mercy, Peace',
            'Obedience',
            'Patience',
            'Praise',
            'Prayer',
            'Promises',
            'Protection',
            'Repentance, Reconciliation',
            'Thankfulness, Joy',
            'Trials, Trust',
            'Unity',
            'Worship',
            'Youth',
            'Zeal',
        ];

        Tag::query()->upsert(
            collect($sermonTags)->map(fn (string $name) => [
                'name' => $name,
                'type' => Tag::TYPE_SERMON,
            ])->merge(
                collect($hymnTags)->map(fn (string $name) => [
                    'name' => $name,
                    'type' => Tag::TYPE_HYMN,
                ])
            )->values()->all(),
            uniqueBy: ['name', 'type']
        );
    }
}
